export const DISHES3 =
    [
        {
        id: 0,
        name:'Red Velvet Cake',
        image: 'assets/images/redvelvet.jpeg',
        category: 'mains',
        label:'Hot',
        price:'Rs. 499',
        description:'Kit Kat Candy Bar Cake is a chocolate layer cake with chocolate buttercream frosting, surrounded by Kit Kat candy bars, then topped with M&M s and tied with a big bow for a festive, fun party cake',
           },
        {
        id: 1,
        name:'Pink Velvet Cake',
        image: 'assets/images/pinkvelvet.jpg',
        category: 'appetizer',
        label:'',
        price:'1.99',
        description:'Deep fried Zucchini coated with mildly spiced Chickpea flour batter accompanied with a sweet-tangy tamarind sauce',
        },
        {
        id: 2,
        name:'Cookies and Cream',
        image: 'assets/images/cookiescream.jpg',
        category: 'appetizer',
        label:'New',
        price:'1.99',
        description:'A quintessential ConFusion experience, is it a vada or is it a donut?',
        },
        {
        id: 3,
        name:'Gulab Jamun Cake',
        image: 'assets/images/gulabjamun.jpg',
        category: 'dessert',
        label:'',
        price:'2.99',
        description:'A delectable, semi-sweet New York Style Cheese Cake, with Graham cracker crust and spiced with Indian cardamoms',
        },
        {
        id: 4,
        name:'Rasmalai Cake',
        image: 'assets/images/rasmalai.jpeg',
        category: 'dessert',
        label:'',
        price:'2.99',
        description:'A delectable, semi-sweet New York Style Cheese Cake, with Graham cracker crust and spiced with Indian cardamoms',
        },
        {
        id: 5,
        name:'Chocolate Decadent Cake',
        image: 'assets/images/chocolatedecadent.jpeg',
        category: 'dessert',
        label:'',
        price:'2.99',
        description:'A delectable, semi-sweet New York Style Cheese Cake, with Graham cracker crust and spiced with Indian cardamoms',
        },
        {
        id: 6,
        name:'Kitkate Cake',
        image: 'assets/images/kitkat.jpeg',
        category: 'dessert',
        label:'',
        price:'2.99',
        description:'A delectable, semi-sweet New York Style Cheese Cake, with Graham cracker crust and spiced with Indian cardamoms',
        }
    ];